#!/usr/bin/env ruby

require "bundler/setup"
require "telegram/bot"

MESSAGE_TEXT = "Kennst du schon unsere Signal Gruppe? https://signal.group/#CjQKIDtQOJDwton59Nd01xxuI7WhucPQQcVmJ9xUEQ7BXUFiEhCjfgiL37OiNwK_eiekJ9qh"

Telegram::Bot::Client.run(ENV.fetch("TELEGRAM_TOKEN")) do |bot|
  bot.listen do |message|
    bot.api.send_message(chat_id: message.chat.id, text: MESSAGE_TEXT)
  end
end
