version: "3.9"
services:
  bot:
    build:
      context: .
      target: dev
    env_file:
      - .env.dev
    stdin_open: true
    tty: true
    command: ./bot
    volumes:
      - ".:/app"
      - bundle:/bundle
volumes:
  bundle:
