version: "3.9"
services:
  bot:
    build:
      context: .
      target: dev
    env_file:
      - .env.dev
    stdin_open: true
    tty: true
    command: bundle exec bot
    volumes:
      - ".:/app"
      - bundle:/bundle
    # ports:
    #   - "3000:3000"
volumes:
  bundle:
